apiVersion: apps/v1

kind: Deployment
metadata:
  name: keygenrator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: keygenrator
  template:
    metadata:
      labels:
        app: keygenrator
    spec:
      containers:
        - name: keygenrator
          image: akashkumar2k10/keygenrator:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health 
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10  
---
apiVersion: v1
kind: Service
metadata:
  name: keygenrator-service
spec:
  type: NodePort   # ClusterIP,NodePort,LoadBalancer
  selector:
    app: keygenrator
  ports:
    - protocol: TCP
      port: 8080  # Service port
      targetPort: 8080  # Container port
      nodePort: 30080  # Expose on a NodePort (30000-32767)
