
spring.application.name=Urlshortner

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/


# server.address=0.0.0.0
spring.datasource.url=jdbc:mysql://localhost:3308/UrlShortner?serverTimezone=UTC&sslmode=required

#url.shortner.default.url = http://192.168.0.107:8081
url.shortner.default.url = http://localhost:8081
frontend.url=http://localhost:4200
#frontend.url=http://192.168.0.107:4200


spring.datasource.username=root
spring.datasource.password=rootpassword
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
# spring.jpa.hibernate.ddl-auto=update
server.port = 8081

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

management.endpoints.web.exposure.include=*
