# Use the official OpenJDK image as the base image
FROM openjdk:17-jdk



# Create the application home directory
RUN mkdir -p app

# Copy the Spring Boot JAR file into the application home directory
COPY target/UrlShortner.jar app/UrlShortner.jar

# Expose the port that the application runs on
EXPOSE 8081

# Generate the JAR file and start the application
CMD ["java", "-jar", "app/UrlShortner.jar"]